### ISSUE TITLE
go/src/github.com/fragglet/ipxbox/ppp/session.go:365:6: undefined: errors.Is

### ISSUE THREAD

**Issue by skadarnold** [fragglet/ipxbox#12] opened 2022-01-17 21:03 UTC
When following the how to guide and `go get github.com/fragglet/ipxbox` command. I had ipxbox installed originally but wanted to upgrade to allow PPTP tunneling and this error happens when trying to install.

**Comment by skadarnold** [comment] 2022-01-19 17:51
I was able to fix this error and build by using ubuntu 20.04 and go version 1.13.8. 

This error seems to occur with ubuntu 18.04 and using go version 1.10.4. I am not sure if using go version 1.13.8 on ubuntu 18.04 would also work, but will try to test at some point.

**Comment by fragglet** [comment] 2022-02-22 20:26
Yes, this bug is caused by using a very old version of Go, and is fixed by updating to a newer version. If really necessary I believe you can change that line to:
```go
if err == io.ErrClosedPipe {
```

**Closed by fragglet** 2022-02-22 20:26 UTC
